---

- name: Install Apache2
  apt:
    name: apache2
    state: latest 

- name: Custom LogFormat definition for IP sanitization 
  blockinfile:
    path: /etc/apache2/apache2.conf
    block: |
      LogFormat "%v:%p 192.168.1.4 %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" ipv4_log
      LogFormat "%v:%p fd00::6 %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" ipv6_log
      LogFormat "%v:%p 127.0.0.42 %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" onion_log

- name: Create virtual hosts directory if that does not exists
  ansible.builtin.file:
    path: "/var/www/{{ item.servername }}"
    state: directory
    mode: '0755'
  loop: "{{ domain_names }}"

- name: Create virtual host files
  ansible.builtin.template:
    src: virtual_host.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.servername }}.conf"
    owner: root
    group: root
  loop: "{{ domain_names }}"

- name: Enable "{{ item.servername }}.conf"
  command: sudo a2ensite "{{ item.servername }}.conf"
  #notify:
  #- restart apache2
  loop: "{{ domain_names }}"


- name: Disable the default site defined in 000-default.conf
  command: sudo a2dissite 000-default.conf
  notify:
  - restart apache2